AWSTemplateFormatVersion: "2010-09-09"

Description: One RDS database (no Internet access) and one EC2 instance with ssh access from Internet

Parameters:
  StackName:
    Type: String
  Cidr:
    Type: String
    Default: 172.31.0.0/24
  DMZCidr:
    Type: String
    Default: 172.31.0.0/25
  PrivateCidr:
    Type: String
    Default: 172.31.0.128/25


Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: Cidr

  DMZSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: DMZCidr

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock:
        Ref: PrivateCidr

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC

  Route:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: DMZSubnet
      RouteTableId:
        Ref: PublicRouteTable

  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnet
      RouteTableId:
        Ref: PrivateRouteTable

  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: VPC

  InboundSSHNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: NetworkAcl
      RuleNumber: '101'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '22'
        To: '22'
  
  InboundResponsePortsNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: NetworkAcl
      RuleNumber: '102'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '1024'
        To: '65535'

  OutBoundNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: NetworkAcl
      RuleNumber: '100'
      Protocol: '6'
      RuleAction: allow
      Egress: 'true'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '0'
        To: '65535'

  SubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Ref: DMZSubnet
      NetworkAclId:
        Ref: NetworkAcl

  DMZSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: DMZ security group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '0'
        ToPort: '65535'
        CidrIp: 0.0.0.0/0

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Basic permissive security group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '0'
        ToPort: '65535'
        CidrIp: 0.0.0.0/0

  PublicIPAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  VPNIPAddressAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt PublicIPAddress.AllocationId
      NetworkInterfaceId:
        Ref: DMZPublicNIC

  DMZPublicNIC:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId:
        Ref: DMZSubnet
      Description: Internet facing NIC
      GroupSet: 
      - Ref: DMZSecurityGroup
      SourceDestCheck: true

  DMZPrivateNIC:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId:
        Ref: PrivateSubnet
      Description: Private facing NIC
      GroupSet: 
      - Ref: PrivateSecurityGroup
      SourceDestCheck: true


  DMZInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-a60c23b0
      InstanceType: t2.micro
      KeyName: default-ssh-key
      NetworkInterfaces:
      - NetworkInterfaceId:
          Ref: DMZPublicNIC
        DeviceIndex: 0
      - NetworkInterfaceId:
          Ref: DMZPrivateNIC
        DeviceIndex: 1

  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-a60c23b0
      InstanceType: t2.micro
      KeyName: bastion-key
      NetworkInterfaces:
      - AssociatePublicIpAddress: false
        DeleteOnTermination: true
        DeviceIndex: 0
        SubnetId:
          Ref: PrivateSubnet
        GroupSet:
        - Ref: PrivateSecurityGroup

Outputs:
  DMZSecurityGroup:
    Value:
      Ref: DMZSecurityGroup
  PrivateSecurityGroup:
    Value:
      Ref: PrivateSecurityGroup
  VPC:
    Value:
      Ref: VPC
  DMZSubnet:
    Value:
      Ref: DMZSubnet
  PrivateSubnet:
    Value:
      Ref: PrivateSubnet
  PublicRouteTable:
    Value:
      Ref: PublicRouteTable
  PrivateRouteTable:
    Value:
      Ref: PrivateRouteTable
  DMZInstance:
    Value:
      Ref: DMZInstance
  DMZInstance:
    Value:
      Ref: PrivateInstance
